---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kali-linux
  labels:
    app: pentesting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pentesting
        run: kali-linux
    spec:
      containers:
      - image: kalilinux/kali-linux-docker
        imagePullPolicy: IfNotPresent       ### Always
        name: kali-linux
        stdin: true
        tty: true
---
